version: "3.8"

services:
  wood-calculator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wood-material-calculator
    ports:
      - "6767:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
