services:
  wood-calculator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wood-material-calculator
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge