services:
  wood-calculator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wood-material-calculator
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
